### ISSUE TITLE
How can i find this file(genes_new.txt) 

### ISSUE THREAD

**Issue by baoyulinn** [YangLabHKUST/STitch3D#1]
Dear professor
  I want to know where i can find this file when i try this great STitch3D.
`genes_new = pd.read_csv("./genes_new.txt")` in this part "Run STitch3D on the human heart dataset"

thank you so much

**Comment by gefeiwang** [comment]
Hi there,

"genes_new.txt" was obtained using [ENSEMBL Gene ID to Gene Symbol Converter](https://www.biotools.fr/human/ensembl_symbol_converter/).  You can find this file through [this link](https://drive.google.com/file/d/1OU2vBuKPgCosIrS50UWhvv3zAh8LoY-_/view?usp=sharing). 

Thank you for your interest!

**Comment by baoyulinn** [comment]
Thanks for your link!

I also have another question:
In this step, we need this file (results_6PCW)
`plot3D_clusters(directory = "./results_6PCW",
                clusters = clusters,
                cluster_colors = cluster_colors,
                um = um,
                spot_radius = spot_radius,
                axis_rescale = axis_rescale
                )`
but i just get the file (results_human_heart) in python, which do not include clustering_result.csv
`Error in file(file, "rt") : cannot open the connection
3.
file(file, "rt")
2.
read.table(paste0(directory, "/clustering_result.csv"), sep = ",",
header = TRUE) at plot3D_func.R#74
1.
plot3D_clusters(directory = "./results_human_heart", clusters = clusters,
cluster_colors = cluster_colors, um = um, spot_radius = spot_radius,
axis_rescale = axis_rescale)`
<img width="253" alt="image" src="https://user-images.githubusercontent.com/111479371/223872316-481a3f04-23ed-40e0-8488-c2c7938b9668.png">

**Comment by gefeiwang** [comment]
“clustering_result.csv” is created to visualize clustering results in R. You can get this result by saving the clustering result in the results folder. For example, we ran `model.adata_st.obs["louvain"].to_csv(os.path.join(save_path, "clustering_result.csv"))` after Louvain clustering in the [6 PCW human heart example](https://stitch3d-tutorial.readthedocs.io/en/latest/tutorials/human_heart/STitch3D_human_heart.html).

**Comment by baoyulinn** [comment]
After learning the tutorials, I have got a lot from this great Stitch3D.
But, I did not find the method to express specific gene in spatial.
For example, in this figure
<img width="501" alt="image" src="https://user-images.githubusercontent.com/111479371/224672325-c417cb7f-566d-4bd6-aed5-7a1ab3139057.png">

Can you provide the code or tutorial?

**Comment by gefeiwang** [comment]
We just added an example of differentially gene analysis using 6 PCW and 9 PCW human hearts in our tutorial website. Please check [this link](https://stitch3d-tutorial.readthedocs.io/en/latest/tutorials/human_heart/DE_analysis_smooth_muscle_cell-enriched_regions.html) for more details.

**Comment by baoyulinn** [comment]
Thanks for your reply. 
And i want to know how to express gene in spatial 3D. For example in this following figure
![image](https://user-images.githubusercontent.com/111479371/225026723-d6e7231c-e917-4110-b39f-2ebfd6ecae60.png)

In the tutorials, there are only the way to Visualize 3D spatial regions and Visualize 3D cell-type distributions. I want to know how to Visualize 3D gene expression.

 Thank you so much for carving out time to answer my questions.

**Comment by gefeiwang** [comment]
Hi, you can follow [this code](https://stitch3d-tutorial.readthedocs.io/en/latest/tutorials/human_heart/3d_genes/index.html) to visualize gene expressions in 3D coordinates provided by STitch3D. Thank you for your interest in our package.
