### ISSUE TITLE
where can I download 'seurat_clust_1620.txt' and 'cluster_anno_table.csv' files ?

### ISSUE THREAD

**Issue by Tidebear** [YangLabHKUST/STitch3D#13]
Dear author,
Thank you for your creative work, STitch3D is very practical, but I am very confused about the collection of this data set in the process of use. 

for example, when running STitch3D on the Drosophila embryo dataset, I can't find the two datasets
''/Calderon_2022/seurat_clust_1620.txt''
''Calderon_2022/cluster_anno_table.csv''

If possible, please tell me where these two data respectively come from or where can I download them.
thank you very much！

**Comment by jiazhao97** [comment]
Hi there, 

Thank you for your interest in our STitch3D method! In the example of Drosophila embryo analysis, we annotated cell types for the scRNA-seq data to construct a cell-type reference for the 3D reconstruction. Specifically, we used Seurat to perform clustering, and then assigned cell types for cell clusters based on marker genes. We have uploaded the resulting two files, including seurat_clust_1620.txt and cluster_anno_table.csv, into a Google drive folder. Please use [this link](https://drive.google.com/drive/folders/1aUBsv6_2i0_-guei1pPWrShz4qM5q46I?usp=sharing) to download them.

Best,
Jia

**Comment by Tidebear** [comment]
Dear author,

I have sent the request for file sharing, please accept it.
Thank you very much.

Best,
Lu

**Comment by jiazhao97** [comment]
Hi Lu,

I have made the folder publicly available. Thank you again for your interest!

Best,
Jia
