### ISSUE TITLE
Cannot find CCFv3 dataset

### ISSUE THREAD

**Issue by cristalliao** [YangLabHKUST/STitch3D#14]
Dear Professor,
I want to know where I can find this file when I try this great STitch3D.
#3D coordinates and model are based on CCFv3.
load("spotstable.RData")
load("VOLUMESMALL.RData")
load("VOLUME.RData")
in this part, "Run STitch3D on the adult mouse brain dataset"
Thank you so much!

**Comment by gefeiwang** [comment]
Hi Cristal,

"spotstable.RData" is a data frame named "spots.table", containing meta information of spots. You can get this data frame by including sources provided by the original publication following [this code](https://github.com/cantin-ortiz/molecular-atlas/blob/master/bin/includes.R). Then run `spots.table <- add.parent.acronym(load.spots.table())` to get the data frame.

"VOLUMESMALL.RData" and "VOLUME.RData" contain 3D mesh models of mouse brain. You can load them by running the following code:
`library(wholebrain)`
`attach(loadNamespace('wholebrain'), warn.conflicts = FALSE)`
which depends on package "wholebrain".

**Comment by cristalliao** [comment]
Dear Gefei,
Thanks for your reply! It is really helpful!! However, I still cannot run the sources provided by the original publication following [this code](https://github.com/cantin-ortiz/molecular-atlas/blob/master/bin/includes.R), the R studio gives me the error: 
<img width="765" alt="Screen Shot 2023-05-09 at 12 47 23 pm" src="https://user-images.githubusercontent.com/128761908/236981147-dd4d9df9-6ff9-4b8b-94fb-f3197469d4ff.png">
Do you know how to deal with this problem? Thanks a lot!
