### ISSUE TITLE
questions of using STitch3D

### ISSUE THREAD

**Issue by MingLi-929** [YangLabHKUST/STitch3D#18]
hi developers, 
Thanks for all of you to develop such a great method for 3D reconstruction. This method helps me a lot in my research.
I come to some problem when i follow the tutorials(https://stitch3d-tutorial.readthedocs.io/en/latest/tutorials/Drosophila_embryo/STitch3D_Drosophila_embryo.html)

1. It seems that you delete the 14th slide. Would you please tell me the reason that you drop the last slide? Is there any standard for me to follow when i deal with my own spatial data.
```
slice_all = sorted(list(set(adata_st_raw.obs['slice_ID'].values)))[:-1]
```

2. i use all of the data you mention in the tuorial(https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190149 and the table you provide in github issue) and i follow the code step by step. when i deal with the scRNA data, i have different umap from you picture. So my question is that the difference come from random or there is some update to the GEO data which make my umap different from u.
![截屏2023-07-21 10 55 52](https://github.com/YangLabHKUST/STitch3D/assets/78794151/579cd2fc-7933-46ba-b9d5-f19b5a75b1ab)

3. The last question is do the annotation to the clusters matters. In your tutorials(https://stitch3d-tutorial.readthedocs.io/en/latest/tutorials/Drosophila_embryo/STitch3D_Drosophila_embryo.html), the finished scRNA data show that there is 16 clusters, which is 
```
sensory nervous system
salivary gland
muscle
CNS
tracheal system
midgut
plasmatocytes
proventriculus
hindgut
yolk nuclei
fat body
epidermis
foregut
oenocyte
amnioserosa
ubiquitous
```
but in the stereoseq h5ad data，there are 10 clusters
![截屏2023-07-21 11 00 41](https://github.com/YangLabHKUST/STitch3D/assets/78794151/7a838a1b-f83b-43ed-ac94-060aa60c8b86)
```
['salivary gland', 'epidermis', 'CNS', 'carcass', 'fat body', 'muscle', 'trachea', 'midgut', 'hemolymph', 'foregut']
Categories (10, object): ['salivary gland', 'epidermis', 'CNS', 'carcass', ..., 'trachea', 'midgut', 'hemolymph', 'foregut']
```
The number and the name is different, like 'trachea' in ST annotation and the 'tracheal system' in scRNA annotaion.
There is carcass in ST data but there is no in scRNA data.

My question is that if the annotation mater, there should  be no difference between scRNA and ST. If annotation does not matter, can i only cluster the scRNA and name the cluster by random name like "cell type1", "cell type 2"....

Would u please give some advice about these questions, sincerely thanks in advance!!!

**Comment by MingLi-929** [comment]
Hi Gefei,
Thank u for your rapid reply! I am so grateful to you with your detail explanation. I am using your package in my research and it is such a great work that i wanna recommand to my teamates.

Following your advice, i wanna apologize that i still can not reproduce your result of umap following the tutorial step by step
> So I wonder if there is any problems after normalization steps or pca on your side? Do the data after these steps contain NaNs or Infs?

![image](https://github.com/YangLabHKUST/STitch3D/assets/78794151/4ff2b3e9-50d5-4c82-8f83-1a44c9722265)

![image](https://github.com/YangLabHKUST/STitch3D/assets/78794151/7be69d3c-8b2e-4f49-ac6a-cb37bd88af07)

after normalization steps or pca, there is no such abnormal values.

It should be admittd that all you code is the standard workflow of clustering scRNA, like normalization, pca, umap and neighbors. And the workflow help me to correctly cluster all my scRNA data except [GSE190147](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190147). 

I wanna make sure one thing. The data from [GSE190147](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190147) is the Supplementary data from the bottom of the html.
![image](https://github.com/YangLabHKUST/STitch3D/assets/78794151/11c48ee9-39fc-45d6-837a-45c72f711d31)

and follow the code in your tutorial step by step can get the ump like u? if there is any thing i need to do out of the turtorial? 

I am very sorry to interrupt u with such a stupid question, but the umap result is an important key for me to validate the scRNA data. Since it should be a normal scRNA data as input can lead to a valid 3D reconstruction model.

Would u please send me an cloud link , which includes all of the data used in the tutorial and all of the python code you used to produce the umap. If the data and the code was the same, there must be some bug or anything strange with my computer. 

And the last thing i wanna to ask for you help is that
> 1. According to the tutorial, it is the adata_ref_umap rather than adata_ref is going to be normalized. But it is adata_ref rather than adata_ref_umap to be passed to Stitch3D. Can I get the understanding that, the only thing i need to pass to Stitch3D is the scRNA data, even it is not normalized ? 
> 2. More over, Is it necessary to do clustering for the scRNA data , which is passed to Stitch3D? 

Your package is so important to me that i need to pay attention to every details i coverd. Again, sorry to interrupt u and sincere thanks to you inadvance!!!

**Comment by gefeiwang** [comment]
Hi,

Thank you for checking the data! It is strange if such a umap plot occurs when there are no NaNs in the data. 

> I wanna make sure one thing. The data from [GSE190147](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190147) is the Supplementary data from the bottom of the html.

- Yes, we simply downloaded the data from "Supplementary file" and unzipped them.

> and follow the code in your tutorial step by step can get the ump like u? if there is any thing i need to do out of the turtorial?

- There are no extra steps needed for the experiment, so all the steps are in the tutorial and all the data required are in [GSE190147](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190147) and [this link](https://drive.google.com/drive/folders/1aUBsv6_2i0_-guei1pPWrShz4qM5q46I?usp=sharing).

I have also uploaded another jupyter notebook file in [this link](https://drive.google.com/drive/folders/1Zpfm17iL3tw9bUu9reA4XVzc3DzopqXy?usp=sharing) for checking the single-cell data, in which we downloaded the data again and saved in the "update" folder. But all the code and results are just the same with the tutorial.

However, as you mentioned, 

> Can I get the understanding that, the only thing i need to pass to Stitch3D is the scRNA data, even it is not normalized ?

Indeed the umap plot in our tutorial is just for visualization of clusters, which is not necessary for running STitch3D. It is also not necessary to do clustering for the scRNA data if we already have cell-type labels. Therefore, if the umap plot is still not normal, maybe you can run the next steps without showing umap.

Best,
Gefei

**Comment by MingLi-929** [comment]
Hi, geifei,
Thanks for your patient explanation ~
After a get your explanation, i still can not reproduce the umap and i dig into this bug. Eventually, i found that is bug is related to the version of scanpy and umap.[link](https://github.com/scverse/scanpy/issues/2045).

i change my scanpy from 1.7.2 to 1.9.1, which helps me solve this bug.
![image](https://github.com/YangLabHKUST/STitch3D/assets/78794151/cd10e830-8fdf-42d0-b3b6-036c1bfb3e39)

I can not make the judgement that this problem absolutely came from scanpy, but in my side scanpy(1.7.2) actually resulted in the bug. So maybe my bug will give u a hint about the dependency of STitch3D, which require scanpy==1.7.2.
And i did not test the rest code with scanpy 1.9.1, which may lead to conflicts. So it is just a hint!

At last, thank you for developing such a great package and your patient explanation!

Regards,
