### ISSUE TITLE
Run without single cell RNA data?

### ISSUE THREAD

**Issue by vladimirkovacevic** [YangLabHKUST/STitch3D#2]
I understand reference single-cell RNA dataset is necessary to perform cell-type deconvolution but just wanted to ask whether STitch3D has some mode or possibility to calculate 3D domains only with ST slices. So, is it possible to run it with only ST data?

**Comment by gefeiwang** [comment]
Hi,

Thank you for your interest in STitch3D. A reference single-cell RNA dataset is a necessary part in STitch3D's modeling, so STitch3D cannot be run only with ST slices.
