### ISSUE TITLE
Mouse brain dataset

### ISSUE THREAD

**Issue by Super-LzzZ** [YangLabHKUST/STitch3D#28]
Dear Professor,
Thanks for your explanation and patience !  
In the example1 of tutorials, When loading the single cell reference dataset about the file "./data/MouseBrain/all_cells_20200625.h5ad" and ". /data/MouseBrain/snRNA_annotation_astro_subtypes_refined59_20200823.csv", is it possible to get them directly or should I go through some kind of processing to get them ?

Thanks !

**Comment by gefeiwang** [comment]
Hi Zhongming,

You can use the following code to get the data: 
`wget https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/all_cells_20200625.h5ad`; 
`wget https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/snRNA_annotation_astro_subtypes_refined59_20200823.csv`

Best,
Gefei
