### ISSUE TITLE
How can I find the file "all_cells_20200625.h5ad" and "snRNA_annotation_astro_subtypes_refined59_20200823.csv"?

### ISSUE THREAD

**Issue by cristalliao** [YangLabHKUST/STitch3D#3]
Dear Professor,
    I want to know where I can find this file when I try this great STitch3D.
adata_ref = ad.read_h5ad("./data/MouseBrain/all_cells_20200625.h5ad") and labels = pd.read_csv("./data/MouseBrain/snRNA_annotation_astro_subtypes_refined59_20200823.csv", index_col=0) in this part "Run STitch3D on the adult mouse brain dataset".
    Thanks in advance!

**Comment by jiazhao97** [comment]
Hi there,

Thank you for your interest in our STitch3D method! 

We obtained the mouse brain snRNA-seq reference from cell2location paper. The two files you mentioned can be accessed through these two links: [https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/all_cells_20200625.h5ad](https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/all_cells_20200625.h5ad), [https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/snRNA_annotation_astro_subtypes_refined59_20200823.csv](https://cell2location.cog.sanger.ac.uk/tutorial/mouse_brain_snrna/snRNA_annotation_astro_subtypes_refined59_20200823.csv). See [this website](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_estimating_signatures.html) for more details.

Best,
Jia

**Comment by cristalliao** [comment]
Dear Jia,
Thanks a lot! This problem has been solved. However, I still cannot find the dataset "slicestable.tsv" when I run the code. Could you tell me where can I find it? Thanks in advance!

**Comment by gefeiwang** [comment]
This issue is discussed in https://github.com/YangLabHKUST/STitch3D/issues/5#issuecomment-1515931760.

> Dear Jia,
> 
> Thanks a lot! This problem has been solved. However, I still cannot find the dataset "slicestable.tsv" when I run the code. Could you tell me where can I find it? Thanks in advance!
> 
> Best regards, Cristal
