### ISSUE TITLE
Cannot import the STitch3D package, how to solve this problem?

### ISSUE THREAD

**Issue by cristalliao** [YangLabHKUST/STitch3D#4]
Dear Professor,
    I really like this STitch3D package and want to run this package on my computer. And I have already followed the tutorials you provided to import the STitch3D package
`git clone https://github.com/YangLabHKUST/STitch3D.git`
`cd STitch3D`
`conda env update --f environment.yml`
`conda activate stitch3d`
    However, when I import this STitch3D package, it gives me some errors, which are 

> import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.

How to deal with this issue? Thanks in advance! Very appreciated!

**Comment by gefeiwang** [comment]
Hi there,

This error seems to be caused by running a bash script instead of a python script. You can try suggestions in [this page](https://stackoverflow.com/questions/19507096/python-error-import-unable-to-open-x-server) to solve it.

Best,
Gefei

**Comment by cristalliao** [comment]
Dear Gefei,

Thanks for your advice! My problem has been solved!

Best regards,
Cristal
