### ISSUE TITLE
How can I find the file "slicestable.tsv"?

### ISSUE THREAD

**Issue by cristalliao** [YangLabHKUST/STitch3D#5]
Dear Professor,
I want to know where I can find this file "slicestable.tsv" when I try this great STitch3D.
meta_slice = pd.read_csv("./data/molecular-atlas-master/data/slicestable.tsv",
                        index_col=0, sep="\t")
in this part "Run STitch3D on the adult mouse brain dataset".
Thanks in advance!

**Comment by gefeiwang** [comment]
Hi Cristal,

"slicestable.tsv" is publicly available at the repository [https://github.com/cantin-ortiz/molecular-atlas](https://github.com/cantin-ortiz/molecular-atlas). You need to download the data files through [https://www.molecularatlas.org/data-to-download/intermediary_data/figures.zip](https://www.molecularatlas.org/data-to-download/intermediary_data/figures.zip) and rename the unzipped folder as "data".

**Comment by cristalliao** [comment]
Thanks a lot!
