### ISSUE TITLE
Cannot run the code in "Visualizing results in 2D" and save "clustering_result.csv"

### ISSUE THREAD

**Issue by cristalliao** [YangLabHKUST/STitch3D#7]
Dear Professor,
     I want to know what is the problem with Example 2 in "Visualizing results in 2D". I encountered several problems when I try this great STitch3D in Example 2.
`
sc.pp.neighbors(model.adata_st, use_rep='latent', n_neighbors=30)
sc.tl.louvain(model.adata_st, resolution=0.5)
model.adata_st.obs["louvain"].to_csv(os.path.join(save_path, "clustering_result.csv"))
for i, adata_st_i in enumerate(result):
    adata_st_i.obs["louvain"] = model.adata_st.obs.loc[adata_st_i.obs_names, ]["louvain"]
color = ['#7570b3', '#1b9e77', '#d95f02', '#66a61e', '#e7298a']
plt.rcParams["figure.figsize"] = (4, 4)
for i, adata_st_i in enumerate(result):
    sc.pl.spatial(result[i], img_key="hires", color=["louvain"], palette=color, size=1.5)
`
in this part "Run STitch3D on the human heart dataset".
The following pictures are my encountered problems:
<img width="1095" alt="Screen Shot 2023-04-25 at 12 41 03 pm" src="https://user-images.githubusercontent.com/128761908/234161975-a17db024-bb65-47b5-9fca-f6b294350ee0.png">

Thanks in advance!

**Comment by cristalliao** [comment]
Hi Geifei,

     I tried this many times, but it still does not work for my sever computer. Is there any solution for me to solve this problem?
    Thanks in advance! Very appreciated!

Best regards,
Cristal

**Comment by gefeiwang** [comment]
Hi Cristal,

It seems that the leigenalg package version 0.9.1 is incompatible with igraph 0.9.9. You can try to also downgrade leigenalg. We have tested STitch3D using python-igraph==0.9.1, louvain==0.7.0, leidenalg==0.7.0, which do not have the issue you reported.

Best,
Gefei

**Comment by cristalliao** [comment]
Dear Gefei,

    Thanks a lot! This problem has been solved! Very appreciated!

Best regards,
Cristal
